# Generated by Django 2.2.6 on 2019-11-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('Cert_number', models.IntegerField(primary_key=True, serialize=False)),
                ('ID', models.IntegerField()),
                ('Report_number', models.IntegerField()),
                ('Cert_issue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientCode', models.IntegerField()),
                ('ClientName', models.CharField(max_length=50)),
                ('ClientType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ModelNum', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Cell_technology', models.CharField(max_length=50)),
                ('Cell_manufacturer', models.CharField(max_length=50)),
                ('Number_of_cells', models.IntegerField()),
                ('Number_of_cells_in_series', models.IntegerField()),
                ('Number_of_series_strings', models.IntegerField()),
                ('Number_of_diodes', models.IntegerField()),
                ('Product_length', models.FloatField()),
                ('Product_width', models.FloatField()),
                ('Product_weight', models.FloatField()),
                ('Superstrate_type', models.CharField(max_length=50)),
                ('Superstrate_manufacturer', models.CharField(max_length=50)),
                ('Substrate_type', models.CharField(max_length=50)),
                ('Substrate_manufacturer', models.CharField(max_length=50)),
                ('Frame_type', models.CharField(max_length=50)),
                ('Frame_adhesive', models.CharField(max_length=50)),
                ('Encapsulant_type', models.CharField(max_length=50)),
                ('Encapsulant_manufacturer', models.CharField(max_length=50)),
                ('Junction_box_type', models.CharField(max_length=50)),
                ('Junction_box_manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Sequence',
            fields=[
                ('SequenceID', models.IntegerField(primary_key=True, serialize=False)),
                ('Sequence_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Standard',
            fields=[
                ('StandardID', models.IntegerField(primary_key=True, serialize=False)),
                ('Standard_Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Published_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('Middlename', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Jobtitle', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Officephone', models.IntegerField()),
                ('Cellphone', models.IntegerField()),
                ('Prefix', models.CharField(max_length=50)),
                ('Isstaff', models.BooleanField()),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceID', models.IntegerField(primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=250)),
                ('Is_FI_required', models.BooleanField()),
                ('FI_Frequency', models.IntegerField()),
                ('TestStandardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_Standard')),
            ],
        ),
        migrations.CreateModel(
            name='Performance_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Max_system_voltage', models.FloatField()),
                ('Open_circuit_voltage_VOC', models.FloatField()),
                ('Short_circuit_current_ISC', models.FloatField()),
                ('Voltage_at_max_power_VMP', models.FloatField()),
                ('Current_at_max_power_IMP', models.FloatField()),
                ('Max_power_output_PMP', models.FloatField()),
                ('Fill_factor_FF', models.FloatField()),
                ('ModelNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('Test_Sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_Sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address1', models.CharField(max_length=50)),
                ('Address2', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Postalcode', models.IntegerField()),
                ('Country', models.CharField(max_length=50)),
                ('Phonenumber', models.IntegerField()),
                ('Faxnumber', models.IntegerField()),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Factory_Inspection',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ReportNum', models.IntegerField()),
                ('Date', models.DateField()),
                ('Inspection_sequence', models.IntegerField()),
                ('Findings', models.CharField(max_length=50)),
                ('Cert_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Certificate')),
                ('Inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
                ('LocID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification', models.CharField(max_length=50)),
                ('StandardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_Standard')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserTbl')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='LocationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Location'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='Test_Standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_Standard'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserTbl'),
        ),
    ]
