# Generated by Django 2.2.6 on 2019-11-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Location')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
            ],
        ),
    ]
