# Generated by Django 2.2.6 on 2019-11-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientCode', models.IntegerField()),
                ('ClientName', models.CharField(max_length=50)),
                ('ClientType', models.CharField(max_length=50)),
            ],
        ),
    ]
