# Generated by Django 2.2.6 on 2019-11-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ModelNum', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Cell_technology', models.CharField(max_length=50)),
                ('Cell_manufacturer', models.CharField(max_length=50)),
                ('Number_of_cells', models.IntegerField()),
                ('Number_of_cells_in_series', models.IntegerField()),
                ('Number_of_series_strings', models.IntegerField()),
                ('Number_of_diodes', models.IntegerField()),
                ('Product_length', models.FloatField()),
                ('Product_width', models.FloatField()),
                ('Product_weight', models.FloatField()),
                ('Superstrate_type', models.CharField(max_length=50)),
                ('Superstrate_manufacturer', models.CharField(max_length=50)),
                ('Substrate_type', models.CharField(max_length=50)),
                ('Substrate_manufacturer', models.CharField(max_length=50)),
                ('Frame_type', models.CharField(max_length=50)),
                ('Frame_adhesive', models.CharField(max_length=50)),
                ('Encapsulant_type', models.CharField(max_length=50)),
                ('Encapsulant_manufacturer', models.CharField(max_length=50)),
                ('Junction_box_type', models.CharField(max_length=50)),
                ('Junction_box_manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Standard',
            fields=[
                ('StandardID', models.IntegerField(primary_key=True, serialize=False)),
                ('Standard_Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Published_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address1', models.CharField(max_length=50)),
                ('Address2', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Postalcode', models.IntegerField()),
                ('Country', models.CharField(max_length=50)),
                ('Phonenumber', models.IntegerField()),
                ('Faxnumber', models.IntegerField()),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('ID', models.IntegerField()),
                ('Cert_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Report_number', models.IntegerField()),
                ('Cert_issue_date', models.DateField()),
                ('ContactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client')),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Location')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Product')),
                ('Test_Standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Test_Standard')),
            ],
        ),
    ]
