# Generated by Django 2.2.7 on 2019-12-06 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0002_certificate_location_product_test_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('Middlename', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Jobtitle', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Officephone', models.IntegerField()),
                ('Cellphone', models.IntegerField()),
                ('Prefix', models.CharField(max_length=50)),
                ('Isstaff', models.BooleanField()),
                ('ClientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client')),
            ],
        ),
    ]
